### ISSUE TITLE
Modded bows?

### ISSUE THREAD

**Issue by cec1Ie** [Fourmisain/PerfectAccuracy#3]
Is there a way to make the mod work with modded bows/projectiles? It currently only seems to apply to vanilla items

**Comment by Fourmisain** [comment]
Has been a while since I looked at this mod (3 years!).
I remember I specifically changed all vanilla items to remove the "divergence" of shot projectiles and was already thinking back then "I wish I could do this more generally". It works for some modded items but not all.

Well, I just looked at the code again.
Projectiles have an owner, so when the divergence is set I can simply check if the owner is a player and set it to 0 across the board!

Took a while to test it on different Minecraft versions.
I found a way to make the mod compatible with 1.16-1.20, which is really nice as well!

1.3 is up!
Lemme know if there's any issues.

**Comment by cec1Ie** [comment]
Thank you so much for a quick response and quick update, and it all works!! You're the best
